apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-scala-poc2
  namespace: spark
spec:
    type: Scala
    mode: cluster
    image: "docker.io/arpitjai/firstsparkscla:1.0.3"
    imagePullPolicy: Always
    mainClass: org.example.firstpoc
    mainApplicationFile: "local:///app/firstscalaspark-1.0-SNAPSHOT-jar-with-dependencies.jar"
    sparkVersion: "3.0.0"
    restartPolicy:
      type: Never
    driver:
      cores: 1
      coreLimit: "1200m"
      memory: "512m"
      labels:
        version: 3.0.0
      serviceAccount: spark
    executor:
      cores: 2
      instances: 2
      memory: "512m"
      labels:
        version: 3.0.0